
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 08 22:03:08 CST 2018
//----------------------------------------------------

package Compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 6;
  public static final int PR_FOR = 41;
  public static final int O_SLASH_EQUALS = 72;
  public static final int PR_TO = 15;
  public static final int PR_TRUE = 14;
  public static final int O_LEFT_PARENTHESIS = 85;
  public static final int PR_FORWARD = 40;
  public static final int PR_SHORTINT = 18;
  public static final int PR_INT = 34;
  public static final int PR_CHAR = 50;
  public static final int PR_PROGRAM = 24;
  public static final int O_COLON_EQUALS = 70;
  public static final int O_DIV = 48;
  public static final int PR_ELSE = 45;
  public static final int PR_INLINE = 35;
  public static final int PR_LABEL = 33;
  public static final int L_INTEGER = 2;
  public static final int PR_FUNCTION = 39;
  public static final int PR_RECORD = 21;
  public static final int O_SLASH = 73;
  public static final int PR_SET = 19;
  public static final int O_LESS_LESS_EQUALS = 66;
  public static final int PR_END = 44;
  public static final int PR_PROCEDURE = 25;
  public static final int O_RIGHT_PARENTHESIS = 84;
  public static final int O_LESS = 68;
  public static final int PR_DOWNTO = 46;
  public static final int PR_BEGIN = 54;
  public static final int O_MINUS_EQUALS = 75;
  public static final int O_MINUS_MINUS = 76;
  public static final int O_LESS_GREATER = 64;
  public static final int L_STRING = 5;
  public static final int L_CHAR = 3;
  public static final int PR_FILE = 42;
  public static final int O_LESS_LESS = 67;
  public static final int PR_CASE = 51;
  public static final int O_MINUS = 77;
  public static final int O_ASTERISK_EQUALS = 82;
  public static final int PR_BYTE = 52;
  public static final int O_LESS_EQUALS = 65;
  public static final int O_AND = 56;
  public static final int PR_REPEAT = 20;
  public static final int PR_WITH = 9;
  public static final int PR_CONST = 49;
  public static final int PR_BOOLEAN = 53;
  public static final int O_XOR = 7;
  public static final int PR_LONGINT = 32;
  public static final int O_COLON = 71;
  public static final int L_FLOAT = 4;
  public static final int PR_REAL = 22;
  public static final int PR_UNTIL = 12;
  public static final int O_GREATER_GREATER = 60;
  public static final int O_FULL_STOP = 74;
  public static final int PR_DO = 47;
  public static final int PR_TYPE = 13;
  public static final int EOF = 0;
  public static final int PR_READ = 23;
  public static final int O_PLUS_EQUALS = 79;
  public static final int error = 1;
  public static final int PR_STRING = 17;
  public static final int O_RIGHT_SQUARE_BRACKET = 57;
  public static final int PR_FALSE = 43;
  public static final int O_LEFT_SQUARE_BRACKET = 58;
  public static final int PR_NIL = 30;
  public static final int PR_ARRAY = 55;
  public static final int O_PLUS_PLUS = 80;
  public static final int PR_VAR = 11;
  public static final int O_EQUALS = 63;
  public static final int PR_IN = 36;
  public static final int O_OR = 27;
  public static final int O_GREATER_GREATER_EQUALS = 59;
  public static final int O_PLUS = 81;
  public static final int PR_IF = 37;
  public static final int O_ASTERISK = 83;
  public static final int O_GREATER = 62;
  public static final int O_NOT = 29;
  public static final int PR_OF = 28;
  public static final int PR_PACKED = 26;
  public static final int PR_THEN = 16;
  public static final int PR_GOTO = 38;
  public static final int O_GREATER_EQUALS = 61;
  public static final int PR_WRITE = 8;
  public static final int O_COMMA = 78;
  public static final int O_SEMICOLON = 69;
  public static final int PR_WHILE = 10;
  public static final int O_MOD = 31;
}

